# Non-Graded Challenge 5

In [29]:
import numpy as np

**Soal 1. Membuat Tensor**

In [30]:
A = np.array([
    [[[23,50],[7,12]],[[27,67],[99,43]]],
    [[[75,21],[57,12]],[[87,12],[18,84]]]
])
print(A)

[[[[23 50]
   [ 7 12]]

  [[27 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 12]
   [18 84]]]]


In [31]:
A.shape

(2, 2, 2, 2)

**Soal 2. Perkalian Matrix**

In [35]:
Matrix_A = np.array([[23,50,19],
                     [7,12,109],
                     [57,67,98]])
Matrix_B = np.array([[17,],
                     [22,],
                     [19]]) 
print(Matrix_A)
print(Matrix_B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]


In [33]:
Matrix_B.shape

(3, 1)

In [34]:
#Matrix A dikali Matrix B

print(Matrix_A@Matrix_B)

[[1852]
 [2454]
 [4305]]


**Soal 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix**

In [40]:
V = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])

In [44]:
#Transpose matrix

Transpose_V = V.T
print(Transpose_V)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [45]:
#Determinan

Det_V = np.linalg.det(V)
print(Det_V)

131344.0000000002


In [46]:
#Invers

Inv_V = np.linalg.inv(V)
print(Inv_V)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
